class MotivationData {
  static const List<String> motivationalTexts = [
    "Learning a little every day leads to big progress. 📘✨",
    "Mistakes are proof that you're trying! 💪✍️",
    "Your English improves every time you practice. 🗣️📚",
    "Small steps every day create great results. 👣🌟",
    "Believe in yourself — you are doing great! 🌈🔥",
    "Every word you learn brings you closer to fluency. 🧠🔤",
    "Consistency is the key to mastering any language. 🔑📖",
    "Your future self will thank you for learning today. 🙌⏳",
    "Don’t rush — learn at your own pace. 🐢💡",
    "Practice makes progress, not perfection. 🎯📘",
    "You’re smarter than you think and stronger than you know. 🧠💥",
    "One new word a day is still progress. 📝🌱",
    "Success starts with the courage to begin. 🚀🔥",
    "The more you practice, the easier it becomes. 📚➡️😄",
    "Every mistake is a step toward improvement. 🔁📈",
    "Keep going — you're closer than you think. 🛤️💫",
    "You have the power to grow every single day. 🌱⚡",
    "Your dedication will take you far. 🚀🌟",
    "Learning English opens doors to new opportunities. 🔓🌍",
    "Stay curious, stay motivated! 🧐✨",
    "Tiny progress is still progress. Keep moving forward! 🌱➡️🌳",
    "Every session you complete builds your confidence. 🧩🔥",
    "Believe in the process — learning takes time. ⏳✨",
    "Today is a great day to learn something new. 🌞📖",
    "Your effort matters more than perfection. ❤️💪",
    "A little practice today goes a long way tomorrow. 🔁📘",
    "You're building a skill that will last a lifetime. 🧠⏳",
    "Don’t be afraid to make mistakes — they guide you. 🗺️✨",
    "Your journey may be slow, but it’s worth it. 🚶‍♂️💫",
    "Celebrate your small wins — they add up! 🎉📚",
    "Every word you learn is a victory. 🏆📝",
    "Your commitment today shapes your tomorrow. 🧱🌟",
    "Keep your goals in sight — you're getting closer. 🎯🚶‍♂️",
    "The best learners are the most consistent ones. 🔁📖",
    "Learning English is an investment in yourself. 💼🌍",
    "You’re doing better than you think. Trust yourself. 🤝💛",
    "A positive mindset makes learning easier. 😊✨",
    "Your progress is really showing — keep it up! 📈🔥",
    "What you learn today builds your confidence tomorrow. 💬💪",
    "Every challenge makes you stronger. ⚔️🌟",
    "Show up for yourself — even for 5 minutes. ⏱️📘",
    "Stay patient, stay focused, stay learning. 🎧📖",
    "You’ve come this far — don’t stop now. 🛤️🔥",
    "Learning English is your superpower in progress. 🦸‍♂️📚",
    "You’re expanding your world one word at a time. 🌍🔤",
    "Great things take time — keep going. ⏳🌟",
    "Your consistency today builds your fluency tomorrow. 🔁🗣️",
    "You've got this — keep believing in yourself. 💛💥",
    "Every lesson brings you one step closer to your goals. 👣🎯",
  ];
}
